services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}      
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #- POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - './${PGDATA}:/var/lib/postgresql/data'
    restart: always
